// src/App.tsx
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import { invoke } from "@tauri-apps/api/tauri";
import {
    Ui2MainMessageType,
    Ui2MainRequest,
    Ui2MainResponseFor,
} from "@/ipc/ui2Main";
import "./App.css";


async function invokeUi2Main<T extends Ui2MainRequest>(
    request: T
): Promise<Ui2MainResponseFor<T>> {
    return await invoke(request.type, request);
}


function App() {
    const [greetMsg, setGreetMsg] = useState("");
    const [name, setName] = useState("");

    async function greet() {
    // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
        const resp = await invokeUi2Main({
            type: Ui2MainMessageType.UTILS_PING,
            message: name,
        });
        setGreetMsg(resp.message);
    }

    return (
        <div className="container">
            <h1>Welcome to Tauri!</h1>

            <div className="row">
                <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
                    <img src="/vite.svg" className="logo vite" alt="Vite logo" />
                </a>
                <a href="https://tauri.app" target="_blank" rel="noreferrer">
                    <img src="/tauri.svg" className="logo tauri" alt="Tauri logo" />
                </a>
                <a href="https://reactjs.org" target="_blank" rel="noreferrer">
                    <img src={reactLogo} className="logo react" alt="React logo" />
                </a>
            </div>

            <p>Click on the Tauri, Vite, and React logos to learn more.</p>

            <div className="row">
                <div>
                    <input
                        id="greet-input"
                        onChange={(e) => setName(e.currentTarget.value)}
                        placeholder="Enter a name..."
                    />
                    <button type="button" onClick={() => greet()}>
            Greet
                    </button>
                </div>
            </div>
            <p>{greetMsg}</p>
        </div>
    );
}

export default App;

// src/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import GreetUser from '@/components/GreetUser.vue';
</script>

<template>
  <div class="container">
    <h1>Welcome to Tauri!</h1>

    <div class="row">
      <a
        href="https://vitejs.dev"
        target="_blank"
      >
        <img
          src="/vite.svg"
          class="logo vite"
          alt="Vite logo"
        >
      </a>
      <a
        href="https://tauri.app"
        target="_blank"
      >
        <img
          src="/tauri.svg"
          class="logo tauri"
          alt="Tauri logo"
        >
      </a>
      <a
        href="https://vuejs.org/"
        target="_blank"
      >
        <img
          src="./assets/vue.svg"
          class="logo vue"
          alt="Vue logo"
        >
      </a>
    </div>

    <p>Click on the Tauri, Vite, and Vue logos to learn more.</p>

    <p>
      Recommended IDE setup:
      <a
        href="https://code.visualstudio.com/"
        target="_blank"
      >VS Code</a>
      +
      <a
        href="https://github.com/johnsoncodehk/volar"
        target="_blank"
      >Volar</a>
      +
      <a
        href="https://github.com/tauri-apps/tauri-vscode"
        target="_blank"
      >Tauri</a>
      +
      <a
        href="https://github.com/rust-lang/rust-analyzer"
        target="_blank"
      >rust-analyzer</a>
    </p>

    <greet-user />
  </div>
</template>

<style scoped>
.logo.vite:hover {
  filter: drop-shadow(0 0 2em #747bff);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #249b73);
}
</style>
